---
################################################################################
# workspace.init — default variables
################################################################################

# deployer-cli user (required)
DEPLOYER_CLI_USER: "to_define"

# workspace directory (required)
# typically: /home/DEPLOYER_CLI_USER/vedicon.config/CODENAME-SCENARIO
DEPLOYER_CLI__DST_CONFIG_BASE_DIR: "/home/{{ DEPLOYER_CLI_USER }}/vedicon.config"
DEPLOYER_CLI__DST_CONFIG_DIR: "{{ DEPLOYER_CLI__DST_CONFIG_BASE_DIR }}/{{ INFRASTRUCTURE_CODENAME }}-{{ INFRASTRUCTURE_SCENARIO }}"

# infrastructure identification (required)
INFRASTRUCTURE_CODENAME: "to_define"
INFRASTRUCTURE_SCENARIO: "to_define"
